__include__: [
  '../dataset/ricepests_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/m2detr_r50vd_ricepests.yml',
]

output_dir: ./output/ricepests_m2detr_r50

epoches: 200

lr_scheduler:
  type: MultiStepLR
  milestones: [150, 180]
  gamma: 0.1
